# Generated by Django 5.2.7 on 2026-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
