services:
  - type: web
    name: swipebooks-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn kitapprojesi.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kitapprojesi.settings
      - key: PYTHON_VERSION
        value: "3.10"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: swipebooksbackend.onrender.com